import { AdminUser, Team, User, DeviceRegistry } from './types';

export const ADMIN_USERS: Record<string, string> = {
  "CC123": "SERVER",
  "BIT123": "SERVER",
  "CODE": "SERVER",
  "CLUB": "SERVER",
  "ABCD": "SERVER",
  "ADMIN": "SERVER",
  "SURYA": "SERVER",
  "KOWSHI": "SERVER",
  "AHILL": "SERVER",
  "MATHI": "SERVER",
  "SWETHA": "SERVER",
  "HIMA": "SERVER",
  "MOHAN": "SERVER",
  "POOJA": "SERVER",
  "PREETHIKA": "SERVER",
  "HARIESH": "SERVER",
  "LATHIKA": "SERVER",
  "PRAKASH": "SERVER",
  "PRIYA": "SERVER",
  "MITHUN": "SERVER",
  "RAAGHAV": "SERVER",
  "SURIYA": "SERVER",
  "DHARSHAN": "SERVER",
  "MADESH": "SERVER",
  "PRAMILA": "SERVER",
  "JD": "SERVER",
  "PRITHIKA": "SERVER",
  "HARSHA": "SERVER",
  "ANI": "SERVER",
  "HARI": "SERVER",
  "A1234": "SERVER"
};

export const DEPARTMENTS = [
  "AGRICULTURAL ENGINEERING",
  "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE",
  "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING",
  "BIOMEDICAL ENGINEERING",
  "BIOTECHNOLOGY",
  "CHEMISTRY",
  "CIVIL ENGINEERING",
  "COMPUTER SCIENCE AND BUSINESS SYSTEMS",
  "COMPUTER SCIENCE AND DESIGN",
  "COMPUTER SCIENCE AND ENGINEERING",
  "COMPUTER TECHNOLOGY",
  "ELECTRICAL AND ELECTRONICS ENGINEERING",
  "ELECTRONICS AND COMMUNICATION ENGINEERING",
  "ELECTRONICS AND INSTRUMENTATION ENGINEERING",
  "FASHION TECHNOLOGY",
  "FOOD TECHNOLOGY",
  "HUMANITIES",
  "INFORMATION SCIENCE AND ENGINEERING",
  "INFORMATION TECHNOLOGY",
  "MATHEMATICS",
  "MECHANICAL ENGINEERING",
  "MECHATRONICS ENGINEERING",
  "PHYSICAL EDUCATION",
  "PHYSICS",
  "SCHOOL OF MANAGEMENT STUDIES",
  "TEXTILE TECHNOLOGY"
];


export const DEPARTMENT_CODES = {
  "AGRICULTURAL ENGINEERING": "AGRI",
  "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE": "AI&DS",
  "ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING": "AI&ML",
  "BIOMEDICAL ENGINEERING": "BME",
  "BIOTECHNOLOGY": "BT",
  "CHEMISTRY": "CHEM",
  "CIVIL ENGINEERING": "CIVIL",
  "COMPUTER SCIENCE AND BUSINESS SYSTEMS": "CSBS",
  "COMPUTER SCIENCE AND DESIGN": "CSD",
  "COMPUTER SCIENCE AND ENGINEERING": "CSE",
  "COMPUTER TECHNOLOGY": "CT",
  "ELECTRICAL AND ELECTRONICS ENGINEERING": "EEE",
  "ELECTRONICS AND COMMUNICATION ENGINEERING": "ECE",
  "ELECTRONICS AND INSTRUMENTATION ENGINEERING": "EIE",
  "FASHION TECHNOLOGY": "FT",
  "FOOD TECHNOLOGY": "FTCH",
  "HUMANITIES": "HUM",
  "INFORMATION SCIENCE AND ENGINEERING": "ISE",
  "INFORMATION TECHNOLOGY": "IT",
  "MATHEMATICS": "MATH",
  "MECHANICAL ENGINEERING": "MECH",
  "MECHATRONICS ENGINEERING": "MCT",
  "PHYSICAL EDUCATION": "PE",
  "PHYSICS": "PHY",
  "SCHOOL OF MANAGEMENT STUDIES": "SMS",
  "TEXTILE TECHNOLOGY": "TT"
};

// START EMPTY - Admin must add teams
export const INITIAL_TEAMS: Team[] = [];

export const STORAGE_KEYS = {
  USERS: 'cwc_users_v3',
  DEVICES: 'cwc_devices_v3',
  CURRENT_DEVICE_ID: 'cwc_this_device_id',
  CONFIG: 'cwc_config_v3',
  TEAMS: 'cwc_teams_v3',
  CURRENT_SESSION: 'cwc_session_v3' // For persisting login state across refresh
};

export const DUMMY_USERS: User[] = [
  {
    id: 'u1',
    name: 'Arun Kumar',
    rollNo: '7376211CS101',
    dept: 'COMPUTER SCIENCE AND ENGINEERING',
    email: 'arunkumar@bitsathy.ac.in',
    phone: '9876500001',
    gender: 'Male',
    year: '3',
    passwordHash: '12345',
    boundDeviceId: 'dev-u1',
    votes: {},
    lastVotedAt: '2024-03-15T10:30:00.000Z'
  },
  {
    id: 'u2',
    name: 'Deepa M',
    rollNo: '7376221IT102',
    dept: 'INFORMATION TECHNOLOGY',
    email: 'deepa@bitsathy.ac.in',
    phone: '9876500002',
    gender: 'Female',
    year: '2',
    passwordHash: '12345',
    boundDeviceId: 'dev-u2',
    votes: {},
    lastVotedAt: '2024-03-15T11:45:00.000Z'
  },
  {
    id: 'u3',
    name: 'Sanjay R',
    rollNo: '7376201EC103',
    dept: 'ELECTRONICS AND COMMUNICATION ENGINEERING',
    email: 'sanjay@bitsathy.ac.in',
    phone: '9876500003',
    gender: 'Male',
    year: '4',
    passwordHash: '12345',
    boundDeviceId: 'dev-u3',
    votes: {},
    lastVotedAt: undefined
  },
  {
    id: 'u4',
    name: 'Keerthana S',
    rollNo: '7376231BT104',
    dept: 'BIOTECHNOLOGY',
    email: 'keerthana@bitsathy.ac.in',
    phone: '9876500004',
    gender: 'Female',
    year: '1',
    passwordHash: '12345',
    boundDeviceId: null,
    votes: {},
    lastVotedAt: undefined
  },
  {
    id: 'u5',
    name: 'Mohammed F',
    rollNo: '7376211AD105',
    dept: 'ARTIFICIAL INTELLIGENCE AND DATA SCIENCE',
    email: 'mohammed@bitsathy.ac.in',
    phone: '9876500005',
    gender: 'Male',
    year: '3',
    passwordHash: '12345',
    boundDeviceId: 'dev-u5',
    votes: {},
    lastVotedAt: '2024-03-15T09:15:00.000Z'
  },
  {
    id: 'u6',
    name: 'Lakshmi P',
    rollNo: '7376221CE106',
    dept: 'CIVIL ENGINEERING',
    email: 'lakshmi@bitsathy.ac.in',
    phone: '9876500006',
    gender: 'Female',
    year: '2',
    passwordHash: '12345',
    boundDeviceId: null,
    votes: {},
    lastVotedAt: undefined
  },
  {
    id: 'u7',
    name: 'Vikram S',
    rollNo: '7376201ME107',
    dept: 'MECHANICAL ENGINEERING',
    email: 'vikram@bitsathy.ac.in',
    phone: '9876500007',
    gender: 'Male',
    year: '4',
    passwordHash: '12345',
    boundDeviceId: 'dev-u7',
    votes: {},
    lastVotedAt: '2024-03-15T14:20:00.000Z'
  },
  {
    id: 'u8',
    name: 'Anitha K',
    rollNo: '7376211AG108',
    dept: 'AGRICULTURAL ENGINEERING',
    email: 'anitha@bitsathy.ac.in',
    phone: '9876500008',
    gender: 'Female',
    year: '3',
    passwordHash: '12345',
    boundDeviceId: 'dev-u8',
    votes: {},
    lastVotedAt: '2024-03-15T12:00:00.000Z'
  },
  {
    id: 'u9',
    name: 'Kavya M',
    rollNo: '7376231FT109',
    dept: 'FASHION TECHNOLOGY',
    email: 'kavya@bitsathy.ac.in',
    phone: '9876500009',
    gender: 'Female',
    year: '1',
    passwordHash: '12345',
    boundDeviceId: 'dev-u9',
    votes: {},
    lastVotedAt: undefined
  },
  {
    id: 'u10',
    name: 'Surya D',
    rollNo: '7376221CT110',
    dept: 'COMPUTER TECHNOLOGY',
    email: 'surya@bitsathy.ac.in',
    phone: '9876500010',
    gender: 'Male',
    year: '2',
    passwordHash: '12345',
    boundDeviceId: 'dev-u10',
    votes: {},
    lastVotedAt: '2024-03-15T16:45:00.000Z'
  }
];

export const DUMMY_DEVICES: DeviceRegistry = {
  'dev-u1': 'u1',
  'dev-u2': 'u2',
  'dev-u3': 'u3',
  'dev-u5': 'u5',
  'dev-u7': 'u7',
  'dev-u8': 'u8',
  'dev-u9': 'u9',
  'dev-u10': 'u10'
};